import type { Metadata } from 'next';
import '../styles/globals.css'; 

export const metadata : Metadata = {
  title: 'Buzzbip',
  description: 'Generated by Buzzbip',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
